on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check health of Render deployed web app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-p4t4.onrender.com/health
          max-attempts: 3
          retry-delay: 5
          
